crawler:
  start-url: http://183.192.158.118:18100
  valid-patten: http://183.192.158.118:18100
  black-list: 
    - https://hsdev.choicelean.com/webtools/control/ServiceList
    - https://hsdev.choicelean.com/webtools/control/EntityPerformanceTest
    - https://hsdev.choicelean.com/webtools/control/entitymaint
    - https://hsdev.choicelean.com/webtools/control/DeleteGeneric
  login:
    title: 基础开发平台
    username: admin
    password: 123456
  prune:
    tags:
      - head
      - script
      - style
      - nav
      - footer
      - small
    attrs:
      - style
      - align
      - border
      - cellpadding
      - cellspacing
      - href
      - onclick
      - action
      - method
      - bgcolor
    keep-one:
      - select
      - tbody
gen-code: N
agent:
  url: http://localhost:7860
  input-ele: //*[@id="component-10"]/label/textarea
  send-ele: //*[@id="btn-send-style"]
  response-ele: //*[@id="chatbot"]/div[2]/div[2]/div/div[2]/span/p
