crawler:
  start-url: http://183.192.158.118:18100
  valid-patten: http://183.192.158.118:18100
  black-list: 
    - http://183.192.158.118:18100/#
    - http://183.192.158.118:18100/index#
    - http://183.192.158.118:18100/login?logout#
  login:
    title: 基础开发平台
    username: admin
    password: 123456
  prune:
    tags:
      - head
      - script
      - style
      - nav
      - footer
      - small
      - ul
    attrs:
      - style
      - align
      - border
      - cellpadding
      - cellspacing
      - href
      - onclick
      - action
      - method
      - bgcolor
    keep-one:
      - select
      - tbody
    class:
      - hr-line-dashed
      - pace pace-active
      - footer
      - ibox-title
      - row border-bottom white-bg dashboard-header
      - col-sm-2 control-label
      - row border-bottom
      - jstree jstree-3 jstree-default
      - page
gen-code: N
agent:
  url: http://localhost:7860
  input-ele: //*[@id="component-10"]/label/textarea
  send-ele: //*[@id="btn-send-style"]
  response-ele: //*[@id="chatbot"]/div[2]/div[2]/div/div[2]/span/p
